### PR TITLE
[FIX]

### LINKED ISSUE #14: Change types of conversions and reads
In this case is returning string:
https://github.com/kostya05983/rest-bomber/blob/5cd8163ad571c3dc1a0d9454416d1b885991b1ad/parser/readers.go#L18-L31

but where this method is called, the conversion to a slice is used byte:
https://github.com/kostya05983/rest-bomber/blob/5cd8163ad571c3dc1a0d9454416d1b885991b1ad/parser/parser.go#L23

### PR DESCRIPTION
**Pull request by kubitre**
resolve #14 and update Parser structure

### CODE REVIEW

File: parser/parser.go [hunk 1]
```diff
@@ -16,16 +22,15 @@ const (
...
-//Parse json
+//Parse - parsing data from file path and preparing this object to ParserPayload
 func (parser *Parser) Parse(path string) {
 	res := parser.Reader.read(path)
-	var result map[string]interface{}
-	err := json.Unmarshal([]byte(res), &result)
 
-	if err != nil {
+	var payload ParserPayload
+	// var result map[string]interface{}
```
Comment (kostya05983) [inline parser/parser.go:30]: forgot to delete comment

**Review by kostya05983 — APPROVED** [review]

File: parser/parser.go (hunk 1 above)
Comment (kubitre) [reply parser/parser.go:30]: ok
